#!/bin/env bash

#curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh | bash

cd ~/.config

git clone https://github.com/RexAckermann/rexlvim.git

cd lvim

lvim

cd ~/.local/share/lunarvim/lvim/lua/lvim/core/

sed -i "s/layout_strategy = nil/layout_strategy = \'horizontal\'/g" telescope.lua
sed -i 's/layout_config = ..,/layout_config = \{ horizontal = \{ width = 0.9, height = 0.8 \} \},/g' telescope.lua

cd
