#!/bin/env bash

bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh)

cd ~/.config

git clone https://github.com/RexAckermann/rexlvim.git

cd lvim

lvim

sed -i "s/layout_strategy = nil/layout_strategy = \'horizontal\'/g" test/builtin
sed -i 's/layout_config = ..,/layout_config = \{ horizontal = \{ width = 0.9, height = 0.8 \} \},/g' test/builtin
